language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env:
        - COVERAGE=false
        - ARGS="--verbose"
    - python: 3.7
      env:
        - COVERAGE=true
        - ARGS="--verbose --strict"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes true
  - conda config --add channels conda-forge
  - conda update conda
  - conda install nomkl

install:
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION numpy matplotlib pandas metar pytest coverage pytest-mpl pytest-cov pytest-pep8 click --channel=conda-forge
  - source activate testenv
  - pip install coveralls
  - pip install .

script:
  - coverage run --source cloudside check_cloudside.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      coveralls;
    fi
