language: python

matrix:
  fast_finish: true
  include:
    - python: 3.4
      env:
        - COVERAGE=false
    - python: 3.5
      env:
        - COVERAGE=true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update conda --yes

install:
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION seaborn pandas nose coverage
  - source activate testenv
  - conda install --channel=phobson --yes metar
  - pip install coveralls
  - pip install .

script:
  - python check_cloudside.py --with-coverage --cover-package=cloudside --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then coveralls; fi
