package:
  name: cloudside
  version: 0.0.1

source:
  git_url: https://github.com/phobson/cloudside.git
  git_tag: v0.0.1
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1
  script: python setup.py install


requirements:
  build:
    - python
    - setuptools
    - metar
    - matplotlib
    - pandas
    - requests


  run:
    - python
    - metar
    - matplotlib
    - pandas
    - requests

test:
  imports:
    - cloudside

  commands:
    - python -c "import cloudside; cloudside.test()"

  requires:
    - nose

about:
  home: https://github.com/phobson/cloudside.git
  license:  BSD 3-clause
  summary: 'Do stuff with weather data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
